version: '2'

services:
  client:
    container_name: client
    build: ./rest_client
    ports:
      - "5858:5858"
      - "3000:3000"
    volumes:
      - "./rest_client:/usr/src/app"
      - "/usr/src/app/node_modules"
    networks:
      - client
      - bravura1
      # - bravura2

  bravura1:
    container_name: bravura1
    build: ./bravura_instance
    ports:
      - "5841:5840"
      - "4001:4000"
    volumes:
      - "./bravura_instance:/usr/src/app"
      - "/usr/src/app/node_modules"
    networks:
      - client
      - bravura1

  node1:
    container_name: node1
    build: ./node_instance
    ports:
      - "5851:5850"
      - "5001:5000"
    volumes:
      - "./node_instance:/usr/src/app"
      - "/usr/src/app/node_modules"
    networks:
      - bravura1

  # node2:
  #   container_name: node2
  #   build: ./node_instance
  #   ports:
  #     - "5852:5850"
  #     - "5002:5000"
  #   networks:
  #     - bravura1
  #
  # bravura2:
  #   container_name: bravura2
  #   build: ./bravura_instance
  #   ports:
  #     - "5842:5840"
  #     - "4002:4000"
  #   networks:
  #     - client
  #     - bravura2
  #
  # node3:
  #   container_name: node3
  #   build: ./node_instance
  #   ports:
  #     - "5853:5850"
  #     - "5003:5000"
  #   networks:
  #     - bravura2
  #
  # node4:
  #   container_name: node4
  #   build: ./node_instance
  #   ports:
  #     - "5854:5850"
  #     - "5004:5000"
  #   networks:
  #     - bravura2


networks:
  client:
    driver: bridge
  bravura1:
    driver: bridge
  # bravura2:
  #   driver: bridge
