version: '2'

services:
  bravura:
    container_name: bravura
    build: .
    ports:
      - "5858:5858"
      - "3000:3000"
    networks:
      - user_defined

networks:
  user_defined:
    driver: bridge
